# Generated by Django 5.2.13 on 2026-04-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carviewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
