# Generated by Django 6.0.2 on 2026-05-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carlist_carlistitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
